# Generated by Django 6.0.6 on 2026-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_note',
            field=models.FileField(blank=True, null=True, upload_to='messages/video_notes/'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='messages/voice/'),
        ),
    ]
