# Generated by Django 6.0.6 on 2026-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_message_video_note_message_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_music',
            field=models.FileField(blank=True, null=True, upload_to='profile_music/'),
        ),
    ]
